#!/bin/sh
DAEMON=/usr/bin/cosmos-i2cconfig
start ()
{
	echo " Executing cosmos-i2cconfig..."
	start-stop-daemon -S -o -x $DAEMON
}
stop ()
{
	echo " Stopping cosmos-i2cconfig..."
	start-stop-daemon -K -x $DAEMON
}
restart()
{
	stop
	start
}
[ -e $DAEMON ] || exit 1

	case "$1" in
		start)
			start; ;;
		stop)
			stop; ;;
		restart)
			restart; ;;
		*)
			echo "Usage: $0 {start|stop|restart}"
			exit 1
	esac
exit $?